import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';

type BackendResult = { kind: 'response'; response: Response; payload: unknown } | { kind: 'error'; status: 401 | 503; message: string };
function allowedUrl(value: string | undefined) { try { const url = new URL(value || ''); return url.protocol === 'https:' || (url.protocol === 'http:' && (url.hostname === 'localhost' || url.hostname === '127.0.0.1')); } catch { return false; } }
async function backend(path: string, init?: RequestInit): Promise<BackendResult> { const token = (await cookies()).get('admin_session')?.value; const base = process.env.API_BASE_URL; if (!token) return { kind: 'error', status: 401, message: 'Unauthorized.' }; if (!allowedUrl(base)) return { kind: 'error', status: 503, message: 'Admin service is temporarily unavailable.' }; try { const response = await fetch(`${base}${path}`, { ...init, headers: { ...init?.headers, Authorization: `Bearer ${token}` }, cache: 'no-store' }); return { kind: 'response', response, payload: await response.json().catch(() => ({ error: 'Admin service returned an invalid response.' })) }; } catch { return { kind: 'error', status: 503, message: 'Admin service is temporarily unavailable.' }; } }
function forward(result: BackendResult) { return result.kind === 'error' ? NextResponse.json({ error: result.message }, { status: result.status }) : NextResponse.json(result.payload, { status: result.response.status }); }
export async function GET(request: Request) { const input = new URL(request.url).searchParams; const output = new URLSearchParams(); const page = input.get('page') || '1'; const pageSize = input.get('pageSize') || '25'; if (!/^\d+$/.test(page) || !/^\d+$/.test(pageSize) || Number(page) < 1 || Number(pageSize) < 1 || Number(pageSize) > 100) return NextResponse.json({ error: 'Invalid pagination.' }, { status: 400 }); for (const key of ['search', 'role', 'status'] as const) { const value = input.get(key); if (value) output.set(key, value); } output.set('page', page); output.set('pageSize', pageSize); return forward(await backend(`/api/admin/users?${output}`)); }
export async function POST(request: Request) { const body: unknown = await request.json().catch(() => null); if (!body || typeof body !== 'object' || Array.isArray(body)) return NextResponse.json({ error: 'Invalid user data.' }, { status: 400 }); const user = body as Record<string, unknown>; if (typeof user.username !== 'string' || typeof user.email !== 'string' || typeof user.fullName !== 'string' || (user.role !== 'admin' && user.role !== 'manager')) return NextResponse.json({ error: 'Invalid user data.' }, { status: 400 }); const result = await backend('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: user.username, email: user.email, fullName: user.fullName, role: user.role }) }); if (result.kind === 'error') return forward(result); if (!result.response.ok) return forward(result); const payload = result.payload as { data?: Record<string, unknown> }; const data = payload.data; if (!data) return NextResponse.json({ error: 'Admin service returned an invalid response.' }, { status: 502 }); return NextResponse.json({ success: true, data: { id: data.id, username: data.username, email: data.email, fullName: data.fullName, role: data.role, isActive: data.isActive, mustChangePassword: data.mustChangePassword, credentialDelivery: data.credentialDelivery } }, { status: result.response.status }); }
