import { db } from '../../../../../lib/db';
import { requireAuth } from '../../../../../lib/auth';
import { ok, fail, parseId } from '../../../../../lib/http';
import { menuItemUpdateSchema } from '../../../../../lib/validation';
import { audit } from '../../../../../lib/audit';
async function idOf(ctx){const p=await ctx.params;return parseId(p.id)}
export async function GET(request,ctx){const auth=await requireAuth(request);if(!auth.ok)return fail(auth.error,auth.status);const id=await idOf(ctx);if(!id)return fail('Invalid menu item id',400);const[rows]=await db.query(`SELECT mi.id,mi.category_id AS categoryId,mc.name AS categoryName,mi.name,mi.description,mi.price,mi.image_url AS imageUrl,mi.is_popular AS isPopular,mi.is_active AS isActive,mi.sort_order AS sortOrder FROM menu_items mi JOIN menu_categories mc ON mc.id=mi.category_id WHERE mi.id=?`,[id]);return rows[0]?ok(rows[0]):fail('Menu item not found',404)}
export async function PATCH(request,ctx){const auth=await requireAuth(request);if(!auth.ok)return fail(auth.error,auth.status);const id=await idOf(ctx);if(!id)return fail('Invalid menu item id',400);const p=menuItemUpdateSchema.safeParse(await request.json());if(!p.success)return fail('Invalid menu item data',422,p.error.flatten());if(p.data.categoryId!==undefined){const[c]=await db.query('SELECT id FROM menu_categories WHERE id=?',[p.data.categoryId]);if(!c[0])return fail('Category not found',404)}const map={categoryId:'category_id',name:'name',description:'description',price:'price',imageUrl:'image_url',isPopular:'is_popular',isActive:'is_active',sortOrder:'sort_order'},sets=[],vals=[];for(const[k,c]of Object.entries(map))if(p.data[k]!==undefined){sets.push(`${c}=?`);let v=p.data[k];if(k==='isPopular'||k==='isActive')v=v?1:0;vals.push(v)}if(!sets.length)return fail('No fields supplied',400);const[r]=await db.query(`UPDATE menu_items SET ${sets.join(',')} WHERE id=?`,[...vals,id]);if(!r.affectedRows)return fail('Menu item not found',404);await audit(request,auth.user.id,'MENU_ITEM_UPDATED','menu_item',id,p.data);return ok({id,updated:true})}
export async function DELETE(request,ctx){const auth=await requireAuth(request);if(!auth.ok)return fail(auth.error,auth.status);const id=await idOf(ctx);if(!id)return fail('Invalid menu item id',400);const[r]=await db.query('DELETE FROM menu_items WHERE id=?',[id]);if(!r.affectedRows)return fail('Menu item not found',404);await audit(request,auth.user.id,'MENU_ITEM_DELETED','menu_item',id);return ok({id,deleted:true})}
